#!/usr/bin/env python3

from sys import argv
from math import *

def split_argv():
    argv_split = []
    for i in range(len(argv)):
        argv_split.append(argv[i])
        argv_split[i] = argv[i].split("*")
    argv_split.pop(0)
    return argv_split

def calculate_polynomials(poli, x):
    i = 1
    p = 1
    result = int(poli[0])
    while i < len(poli):
        result += int(poli[i])*x**p
        p += 1
        i += 1
    return result

def transfer_function(argv_split):
    j = 0
    x = float(0)
    divider = float(0)
    divisor = float(0)
    result = float (0)
    while x <= 1.001:
        while j < len(argv_split) - 1:
            divider = calculate_polynomials(argv_split[j], x)
            divisor = calculate_polynomials(argv_split[j + 1], x)
            result = result * (divider/divisor)
            j += 2
        j = 0
        print(str('%.3f' %x) + " -> " + str('%.5f' %result))
        result = 1
        x += 0.001

def help():
    print("USAGE")
    print("\t./107transfer [num den]*\n")
    print("DESCRIPTION")
    print("\tnum\tpolynomial numerator defined by its coefficients")
    print("\tden\tpolynomial denominator defined by its coefficients")

def main():
    try:
        if len(argv) > 1 and ((len(argv) - 1) % 2) == 0:
            argv_split = split_argv()
            transfer_function(argv_split)
        elif len(argv) == 2 and argv[1] == '-h':
            help()
        else:
            raise Exception
    except Exception:
        print ("Error")
        exit (84)

if __name__ == "__main__":
    main()