#!/usr/bin/env python3

from sys import argv
from src.help import help
from src.taylor_expansions.checker import taylor_expansions
from src.is_quadratic import is_quadratic

def main():
    try:
        if len(argv) == 2 and argv[1] == '-h':
            help()
        elif is_quadratic() == True:
            taylor_expansions()
        else:
            raise Exception
    except Exception:
        print ("Error")
        exit (84)

if __name__ == "__main__":
    main()